server:
  port: 80
spring:
#  main:
#    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:XE
    username: inoutkrw
    password: 1234
    driver-class-name: oracle.jdbc.driver.OracleDriver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        use_sql_comments: true
        default_schema: BTCKOREADB_OWN
      show-sql: true
  batch:
    initialize-schema: always
logging:
  level:
    com: debug
    org.hibernate:SQL: DEBUG
    org.hibernate.type: trace # SQL